version: "3.8"

services:
  mysql:
    image: mysql:8.0  
    environment:
      MYSQL_DATABASE: "devops"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "flask_user"      # Create a dedicated user
      MYSQL_PASSWORD: "flask_password" 
    volumes:
      - mysql-data-v8:/var/lib/mysql
    networks:
      - two-tier
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uflask_user", "-pflask_password"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    ports:
      - "3306:3306"

  flask:
    image: cultivator404/two-tier-flask:latest
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: flask_user        # Tell Flask to use the new user
      MYSQL_PASSWORD: flask_password # Standard variable for Flask-MySQLdb
      MYSQL_DB: devops
    networks:
      - two-tier
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    depends_on:
      mysql:
        condition: service_healthy
    restart: always

volumes:
  mysql-data-v8:

networks:
  two-tier:
